version: '3.8'

services:
  db:
    image: mysql:8
    container_name: my-app-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
    container_name: my-app
    environment:
      DATABASE_URL: mysql://root:root@db:3306/mydb
    ports:
      - "3003:3003"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db_data:
